//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanarRuralUnan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas()
        {
            this.Diagnosticos_Tratamientos = new HashSet<Diagnosticos_Tratamientos>();
        }
    
        public int IdCita { get; set; }
        public int IdPaciente { get; set; }
        public int IdDoctor { get; set; }
        public Nullable<int> IdHospital { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Plataforma { get; set; }
        public string Estado { get; set; }
        public string Motivo { get; set; }
    
        public virtual Hospitales Hospitale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnosticos_Tratamientos> Diagnosticos_Tratamientos { get; set; }
        public virtual Doctores Doctore { get; set; }
        public virtual Pacientes Paciente { get; set; }
    }
}
