//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SanarRuralUnan
{
    
    public partial class Consultas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultas()
        {
            this.Diagnosticos = new HashSet<Diagnosticos>();
            this.Prescripciones = new HashSet<Prescripciones>();
            this.SignosVitales = new HashSet<SignosVitales>();
        }
    
        public int IdConsulta { get; set; }
        public int IdCita { get; set; }
        public System.DateTime FechaHoraInicio { get; set; }
        public Nullable<System.DateTime> FechaHoraFin { get; set; }
        public string EstadoConsulta { get; set; }
        public string PadecimientoActual { get; set; }
        public string ExamenFisico { get; set; }
        public string Observaciones { get; set; }
        public string PlanSeguimiento { get; set; }
    
        public virtual Citas Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnosticos> Diagnosticos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescripciones> Prescripciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignosVitales> SignosVitales { get; set; }
    }
}
