//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SanarRuralUnan
{
    
    public partial class ContactosEmergencia
    {
        public int IdContactoEmergencia { get; set; }
        public int IdPaciente { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Parentesco { get; set; }
        public string Telefono { get; set; }
        public string Cedula { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
    }
}
