//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanarRuralUnan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosticos_Tratamientos
    {
        public int IdDiagnostico { get; set; }
        public int IdCita { get; set; }
        public int IdEnfermedad { get; set; }
        public int IdMedicamento { get; set; }
        public string PlanTratamiento { get; set; }
        public string Dosis { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    
        public virtual Citas Cita { get; set; }
        public virtual Enfermedades Enfermedade { get; set; }
        public virtual Medicamentos Medicamento { get; set; }
    }
}
