//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SanarRuralUnan
{
    
    public partial class Diagnosticos
    {
        public int IdDiagnostico { get; set; }
        public int IdConsulta { get; set; }
        public Nullable<int> IdEnfermedad { get; set; }
        public string TipoDiagnostico { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Consultas Consultas { get; set; }
        public virtual Enfermedades Enfermedades { get; set; }
    }
}
