//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SanarRuralUnan
{
    
    public partial class DoctorHospitalEspecialidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorHospitalEspecialidad()
        {
            this.Citas = new HashSet<Citas>();
        }
    
        public int IdDoctor { get; set; }
        public int IdHospital { get; set; }
        public int IdEspecialidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual DoctorEspecialidad DoctorEspecialidad { get; set; }
        public virtual Hospitales Hospitales { get; set; }
    }
}
