//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SanarRuralUnan
{
    
    public partial class DoctorEspecialidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorEspecialidad()
        {
            this.DoctorHospitalEspecialidad = new HashSet<DoctorHospitalEspecialidad>();
        }
    
        public int IdDoctor { get; set; }
        public int IdEspecialidad { get; set; }
    
        public virtual Doctores Doctores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorHospitalEspecialidad> DoctorHospitalEspecialidad { get; set; }
        public virtual Especialidades Especialidades { get; set; }
    }
}
