//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SanarRuralUnan
{
    
    public partial class Doctores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctores()
        {
            this.DoctorEspecialidad = new HashSet<DoctorEspecialidad>();
        }
    
        public int IdDoctor { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Cedula { get; set; }
        public string NumeroLicencia { get; set; }
        public string Telefono { get; set; }
        public byte[] Foto { get; set; }
        public string FotoNombre { get; set; }
        public string FotoMimeType { get; set; }
        public bool Estado { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorEspecialidad> DoctorEspecialidad { get; set; }
    }
}
