//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanarRuralUnan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicamentos()
        {
            this.Diagnosticos_Tratamientos = new HashSet<Diagnosticos_Tratamientos>();
        }
    
        public int IdMedicamento { get; set; }
        public string NombreMedicamento { get; set; }
        public string Fabricante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnosticos_Tratamientos> Diagnosticos_Tratamientos { get; set; }
    }
}
