//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SanarRuralUnan
{
    
    public partial class Medicamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicamentos()
        {
            this.Prescripciones = new HashSet<Prescripciones>();
        }
    
        public int IdMedicamento { get; set; }
        public string NombreMedicamento { get; set; }
        public string PrincipioActivo { get; set; }
        public string Concentracion { get; set; }
        public string FormaFarmaceutica { get; set; }
        public string Fabricante { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescripciones> Prescripciones { get; set; }
    }
}
