//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanarRuralUnan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SanarRuralDBEntities : DbContext
    {
        public SanarRuralDBEntities()
            : base("name=SanarRuralDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Comunidades> Comunidades { get; set; }
        public virtual DbSet<Consultas> Consultas { get; set; }
        public virtual DbSet<ContactosEmergencia> ContactosEmergencia { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Diagnosticos> Diagnosticos { get; set; }
        public virtual DbSet<Doctores> Doctores { get; set; }
        public virtual DbSet<DoctorEspecialidad> DoctorEspecialidad { get; set; }
        public virtual DbSet<DoctorHospitalEspecialidad> DoctorHospitalEspecialidad { get; set; }
        public virtual DbSet<Enfermedades> Enfermedades { get; set; }
        public virtual DbSet<Especialidades> Especialidades { get; set; }
        public virtual DbSet<Hospitales> Hospitales { get; set; }
        public virtual DbSet<Medicamentos> Medicamentos { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<Prescripciones> Prescripciones { get; set; }
        public virtual DbSet<RecomendacionesMedicas> RecomendacionesMedicas { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SignosVitales> SignosVitales { get; set; }
        public virtual DbSet<Sintomas> Sintomas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
