//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanarRuralUnan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SanarRuralDBEntities : DbContext
    {
        public SanarRuralDBEntities()
            : base("name=SanarRuralDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Diagnosticos_Tratamientos> Diagnosticos_Tratamientos { get; set; }
        public virtual DbSet<Doctores> Doctores { get; set; }
        public virtual DbSet<Enfermedades> Enfermedades { get; set; }
        public virtual DbSet<Hospitales> Hospitales { get; set; }
        public virtual DbSet<Medicamentos> Medicamentos { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<RecomendacionesMedicas> RecomendacionesMedicas { get; set; }
        public virtual DbSet<Sintomas> Sintomas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
