//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SanarRuralUnan
{
    
    public partial class Prescripciones
    {
        public int IdPrescripcion { get; set; }
        public int IdConsulta { get; set; }
        public int IdMedicamento { get; set; }
        public string Dosis { get; set; }
        public string Frecuencia { get; set; }
        public string Duracion { get; set; }
        public string ViaAdministracion { get; set; }
        public string Indicaciones { get; set; }
        public bool PermiteSustitucion { get; set; }
        public System.DateTime FechaPrescripcion { get; set; }
    
        public virtual Consultas Consultas { get; set; }
        public virtual Medicamentos Medicamentos { get; set; }
    }
}
