//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanarRuralUnan
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecomendacionesMedicas
    {
        public int IdRecomendacion { get; set; }
        public int IdEnfermedad { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Enfermedades Enfermedade { get; set; }
    }
}
