//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SanarRuralUnan
{
    
    public partial class SignosVitales
    {
        public int IdSignosVitales { get; set; }
        public int IdConsulta { get; set; }
        public Nullable<short> PresionSistolica { get; set; }
        public Nullable<short> PresionDiastolica { get; set; }
        public Nullable<short> FrecuenciaCardiaca { get; set; }
        public Nullable<short> FrecuenciaRespiratoria { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<decimal> SaturacionOxigeno { get; set; }
        public Nullable<decimal> PesoKg { get; set; }
        public Nullable<decimal> TallaCm { get; set; }
    
        public virtual Consultas Consultas { get; set; }
    }
}
