using MaterialSkin.Controls;
using SanarRuralUnan.Helpers;

namespace SanarRuralUnan.Views
{
    partial class menuPrincipalMedicos
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.panelBarra = new System.Windows.Forms.Panel();
            this.panelEncabezado = new System.Windows.Forms.Panel();
            this.panelNavegacion = new System.Windows.Forms.Panel();
            this.panelIndicador = new System.Windows.Forms.Panel();
            this.picLogo = new System.Windows.Forms.PictureBox();
            this.lblMarca = new System.Windows.Forms.Label();
            this.lblDescripcion = new System.Windows.Forms.Label();
            this.lblRol = new System.Windows.Forms.Label();
            this.btnPacientes = new MaterialButton();
            this.btnCitas = new MaterialButton();
            this.btnConsultas = new MaterialButton();
            this.btnHistorial = new MaterialButton();
            this.btnCerrarSesion = new MaterialButton();
            this.panelContenido = new System.Windows.Forms.Panel();
            this.lblSeccion = new MaterialLabel();
            this.lblContenido = new MaterialLabel();
            this.panelBarra.SuspendLayout();
            this.panelEncabezado.SuspendLayout();
            this.panelNavegacion.SuspendLayout();
            this.panelContenido.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picLogo)).BeginInit();
            this.SuspendLayout();
            this.panelBarra.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelBarra.Height = 132;
            this.panelBarra.BackColor = Tema.FondoSecundario;
            this.panelBarra.Controls.Add(this.panelNavegacion);
            this.panelBarra.Controls.Add(this.panelEncabezado);
            this.panelEncabezado.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelEncabezado.Height = 76;
            this.panelEncabezado.BackColor = Tema.Superficie;
            this.panelEncabezado.Controls.Add(this.picLogo);
            this.panelEncabezado.Controls.Add(this.lblMarca);
            this.panelEncabezado.Controls.Add(this.lblDescripcion);
            this.panelEncabezado.Controls.Add(this.lblRol);
            this.panelEncabezado.Controls.Add(this.btnCerrarSesion);
            this.picLogo.Location = new System.Drawing.Point(18, 8);
            this.picLogo.Size = new System.Drawing.Size(132, 60);
            this.picLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picLogo.AccessibleName = "Logo de Sanar Rural";
            this.picLogo.AccessibleDescription = "Identidad visual del sistema Sanar Rural";
            this.lblMarca.AutoSize = true;
            this.lblMarca.Location = new System.Drawing.Point(164, 13);
            this.lblMarca.Font = Tema.FuenteMarca;
            this.lblMarca.ForeColor = Tema.AzulOscuro;
            this.lblMarca.Text = "Sanar Rural";
            this.lblDescripcion.AutoSize = true;
            this.lblDescripcion.Location = new System.Drawing.Point(166, 42);
            this.lblDescripcion.Font = Tema.FuenteAyuda;
            this.lblDescripcion.ForeColor = Tema.TextoSecundario;
            this.lblDescripcion.Text = "Atención médica";
            this.lblRol.AutoSize = true;
            this.lblRol.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.lblRol.Location = new System.Drawing.Point(930, 26);
            this.lblRol.Font = Tema.FuenteLabelCampo;
            this.lblRol.ForeColor = Tema.AzulOscuro;
            this.lblRol.Text = "Personal médico";
            this.lblRol.AccessibleName = "Rol actual";
            this.lblRol.AccessibleDescription = "Sesión de atención médica";
            this.panelNavegacion.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelNavegacion.Height = 56;
            this.panelNavegacion.BackColor = Tema.FondoSecundario;
            this.panelNavegacion.Controls.Add(this.btnPacientes);
            this.panelNavegacion.Controls.Add(this.btnCitas);
            this.panelNavegacion.Controls.Add(this.btnConsultas);
            this.panelNavegacion.Controls.Add(this.btnHistorial);
            this.panelNavegacion.Controls.Add(this.panelIndicador);
            this.panelIndicador.BackColor = Tema.VerdeOscuro;
            this.panelIndicador.Location = new System.Drawing.Point(24, 51);
            this.panelIndicador.Size = new System.Drawing.Size(112, 3);
            this.panelIndicador.TabStop = false;
            this.panelIndicador.AccessibleDescription = "Indicador visual de la sección seleccionada";
            this.btnPacientes.Text = "Pacientes";
            this.btnPacientes.Type = MaterialButton.MaterialButtonType.Text;
            this.btnPacientes.Size = new System.Drawing.Size(112, 42);
            this.btnPacientes.TabIndex = 0;
            this.btnPacientes.AccessibleName = "Pacientes";
            this.btnPacientes.AccessibleDescription = "Navegar a la sección Pacientes";
            this.btnPacientes.Click += new System.EventHandler(this.btnPacientes_Click);
            this.btnCitas.Text = "Citas";
            this.btnCitas.Type = MaterialButton.MaterialButtonType.Text;
            this.btnCitas.Size = new System.Drawing.Size(96, 42);
            this.btnCitas.TabIndex = 1;
            this.btnCitas.AccessibleName = "Citas";
            this.btnCitas.AccessibleDescription = "Las citas estarán disponibles cuando se implemente el módulo correspondiente";
            this.btnConsultas.Text = "Consultas";
            this.btnConsultas.Type = MaterialButton.MaterialButtonType.Text;
            this.btnConsultas.Size = new System.Drawing.Size(112, 42);
            this.btnConsultas.TabIndex = 2;
            this.btnConsultas.AccessibleName = "Consultas";
            this.btnConsultas.AccessibleDescription = "Las consultas estarán disponibles cuando se implemente el módulo correspondiente";
            this.btnHistorial.Text = "Historial clínico";
            this.btnHistorial.Type = MaterialButton.MaterialButtonType.Text;
            this.btnHistorial.Size = new System.Drawing.Size(144, 42);
            this.btnHistorial.TabIndex = 3;
            this.btnHistorial.AccessibleName = "Historial clínico";
            this.btnHistorial.AccessibleDescription = "El historial clínico estará disponible cuando se implemente el módulo correspondiente";
            this.btnCitas.Enabled = false;
            this.btnConsultas.Enabled = false;
            this.btnHistorial.Enabled = false;
            this.btnCitas.Click += new System.EventHandler(this.btnFuturo_Click);
            this.btnConsultas.Click += new System.EventHandler(this.btnFuturo_Click);
            this.btnHistorial.Click += new System.EventHandler(this.btnFuturo_Click);
            this.btnCerrarSesion.Text = "Cerrar sesión";
            this.btnCerrarSesion.Type = MaterialButton.MaterialButtonType.Text;
            this.btnCerrarSesion.Size = new System.Drawing.Size(132, 40);
            this.btnCerrarSesion.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.btnCerrarSesion.TabIndex = 4;
            this.btnCerrarSesion.AccessibleName = "Cerrar sesión";
            this.btnCerrarSesion.AccessibleDescription = "Cerrar la sesión actual";
            this.btnCerrarSesion.Click += new System.EventHandler(this.btnCerrarSesion_Click);
            this.panelContenido.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelContenido.BackColor = Tema.Fondo;
            this.panelContenido.Padding = new System.Windows.Forms.Padding(36);
            this.panelContenido.Controls.Add(this.lblSeccion);
            this.panelContenido.Controls.Add(this.lblContenido);
            this.lblSeccion.AutoSize = true;
            this.lblSeccion.Location = new System.Drawing.Point(40, 36);
            this.lblSeccion.FontType = MaterialSkin.MaterialSkinManager.fontType.H5;
            this.lblContenido.AutoSize = true;
            this.lblContenido.ForeColor = Tema.TextoSecundario;
            this.lblContenido.Location = new System.Drawing.Point(42, 92);
            this.lblContenido.MaximumSize = new System.Drawing.Size(850, 0);
            this.lblContenido.FontType = MaterialSkin.MaterialSkinManager.fontType.Body1;
            this.Controls.Add(this.panelContenido);
            this.Controls.Add(this.panelBarra);
            this.BackColor = Tema.Fondo;
            this.ClientSize = new System.Drawing.Size(1280, 800);
            this.MinimumSize = new System.Drawing.Size(1050, 620);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
            this.MaximizeBox = true;
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Name = "menuPrincipalMedicos";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Sanar Rural - Atención médica";
            this.Resize += new System.EventHandler(this.menuPrincipalMedicos_Resize);
            this.panelBarra.ResumeLayout(false);
            this.panelEncabezado.ResumeLayout(false);
            this.panelEncabezado.PerformLayout();
            this.panelNavegacion.ResumeLayout(false);
            this.panelContenido.ResumeLayout(false);
            this.panelContenido.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picLogo)).EndInit();
            this.ResumeLayout(false);
        }

        private System.Windows.Forms.Panel panelBarra;
        private System.Windows.Forms.Panel panelEncabezado;
        private System.Windows.Forms.Panel panelNavegacion;
        private System.Windows.Forms.Panel panelIndicador;
        private System.Windows.Forms.PictureBox picLogo;
        private System.Windows.Forms.Label lblMarca;
        private System.Windows.Forms.Label lblDescripcion;
        private System.Windows.Forms.Label lblRol;
        private MaterialButton btnPacientes;
        private MaterialButton btnCitas;
        private MaterialButton btnConsultas;
        private MaterialButton btnHistorial;
        private MaterialButton btnCerrarSesion;
        private System.Windows.Forms.Panel panelContenido;
        private MaterialLabel lblSeccion;
        private MaterialLabel lblContenido;
    }
}
